### ISSUE TITLE
Add idUser (or similar) as service property

### ISSUE THREAD

**Issue by chsanch** [knownasilya/ember-supabase#8]
Hi, I've been using this package and it works well, thanks for your effort!
I was wondering if it's possible to add a property to easily get the user id of the current session, I've been using: `this.session.data.authenticated.user.id` which does the job, but it would be nice to have a property available, similar as the `isAuthenticated` property.

Thanks and keep with the great job!

**Comment by knownasilya** [comment]
Totally reasonable I think.

**Comment by knownasilya** [comment]
So we don't currently extend the session service, so adding this would be a bit much overhead in my opinion. You could get this by extending the session service in your app and creating a getter called `userId`. Honestly I wish ESA exposed these better.
