### ISSUE TITLE
TypeError: _query$filter.call is not a function

### ISSUE THREAD

**Issue by chsanch** [knownasilya/ember-supabase#9]
Not sure if this issue belong here, but when trying to use a filter query on the store:
```
    return this.store.query('activity', {
      filter: { date: `${dateToQuery}` },
    });
```
I'm getting this error:
```
Uncaught (in promise) TypeError: _query$filter.call is not a function
```

**Comment by knownasilya** [comment]
`filter` is a function, like so:

```ts
return this.store.query('post', {
  include: 'user,comments',
  filter: (ref) => {
    return ref
      .order('created_at', {
        ascending: false,
      })
      .limit(100);
  },
});
```

**Comment by knownasilya** [comment]
See docs for filtering here https://supabase.com/docs/reference/javascript/using-filters

**Comment by chsanch** [comment]
> `filter` is a function, like so:
> 
> ```ts
> return this.store.query('post', {
>   include: 'user,comments',
>   filter: (ref) => {
>     return ref
>       .order('created_at', {
>         ascending: false,
>       })
>       .limit(100);
>   },
> });
> ```

This seems to work, thanks!!
Will close this issue, and maybe will create a PR to update the doc and add this example on the docs 👍

**Comment by knownasilya** [comment]
@chsanch Thanks for bringing this up. By the way there is already a very basic doc for finding records, I added a link to it from the getting started one.
